/**
 ******************************************************************************
 * @file      syscalls.c
 * @brief     System Call Overrides for CN0575 Project
 * @details   This file provides minimal system call implementations for the STM32L496ZG-P
 *            Nucleo board in the CN0575 Single Pair Ethernet (SPE) board project. Overrides
 *            Newlib C library functions for LPUART1 output (via HAL_UART_Transmit) and RTC-based
 *            timekeeping (via HAL_RTC_GetTime/Date), supporting printf logging and SNTP
 *            synchronization in freertos.c when USE_LWIP is defined. Most other syscalls return
 *            errors or stubs as no full OS is present.
 * @addtogroup syscalls System Calls
 * @author    Auto-generated by STM32CubeIDE, modified for CN0575 project
 * @{
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include "usart.h"
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>
#include "rtc.h"


/* Variables */
extern int __io_getchar(void) __attribute__((weak));

/** @brief Environment variables array (empty stub)
  * @details Required by Newlib but unused in CN0575; set to empty array as no environment is needed.
  */
char *__env[1] = { 0 };

/** @brief Pointer to environment variables (stub)
  * @details Points to __env, satisfying Newlib requirements without functionality in CN0575.
  */
char **environ = __env;


/* Functions */
/**
  * @brief Get current time for system use
  * @param [out] tv Pointer to timeval structure for current time
  * @param [in] tzvp Timezone pointer (unused)
  * @return 0 on success
  * @details Retrieves time from RTC (set by SNTP in freertos.c) and converts to UTC seconds since
  *          epoch, used for system time queries in CN0575 when USE_LWIP is defined.
  */
int _gettimeofday(struct timeval *tv, void *tzvp) {
    RTC_DateTypeDef date;
    RTC_TimeTypeDef time;

    HAL_RTC_GetTime(&hrtc, &time, RTC_FORMAT_BIN);
    HAL_RTC_GetDate(&hrtc, &date, RTC_FORMAT_BIN);

    struct tm tm;
    tm.tm_year = date.Year + 100;
    tm.tm_mon = date.Month - 1;
    tm.tm_mday = date.Date;
    tm.tm_hour = time.Hours;
    tm.tm_min = time.Minutes;
    tm.tm_sec = time.Seconds;

    tv->tv_sec = mktime(&tm);
    tv->tv_usec = 0;

    return 0;
}

/**
  * @brief Initialize monitor handles (stub)
  * @details Empty function required by Newlib, unused in CN0575 as no monitor is implemented.
  */
void initialise_monitor_handles()
{
}

/**
  * @brief Get process ID (stub)
  * @return 1 (fixed PID)
  * @details Returns a fixed PID (1) as CN0575 has no multi-process support, satisfying Newlib.
  */
int _getpid(void)
{
  return 1;
}

/**
  * @brief Send signal to process (stub)
  * @param [in] pid Process ID (unused)
  * @param [in] sig Signal number (unused)
  * @return -1 (error)
  * @details Sets errno to EINVAL and returns -1, as CN0575 has no signal handling.
  */
int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

/**
  * @brief Exit program (infinite loop)
  * @param [in] status Exit status (unused)
  * @details Calls _kill and enters an infinite loop, effectively halting CN0575 execution.
  */
void _exit (int status)
{
  _kill(status, -1);
  while (1) {}
}

/**
  * @brief Read from file descriptor (stub)
  * @param [in] file File descriptor (unused)
  * @param [out] ptr Buffer to store read data
  * @param [in] len Number of bytes to read
  * @return Number of bytes read (len)
  * @details Weak stub expecting __io_getchar; unused in CN0575 as input is not implemented.
  */
__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar();
  }

  return len;
}

/**
  * @brief Write to file descriptor via LPUART1
  * @param [in] file File descriptor (unused)
  * @param [in] ptr Buffer containing data to write
  * @param [in] len Number of bytes to write
  * @return 0 on success, -1 on error
  * @details Transmits data via LPUART1 using HAL_UART_Transmit, used for printf logging in CN0575
  *          (e.g., freertos.c, client_mqtt.c), setting errno to EIO on failure.
  */
int _write(int file, char *ptr, int len)
{
    (void)file;

    if (HAL_UART_Transmit(&hlpuart1, (uint8_t*)ptr, len, HAL_MAX_DELAY) != HAL_OK)
    {
        errno = EIO;
        return -1;
    }
    return 0;
}

/**
  * @brief Close file descriptor (stub)
  * @param [in] file File descriptor (unused)
  * @return -1 (error)
  * @details Returns -1 as CN0575 has no file system support, required by Newlib.
  */
int _close(int file)
{
  (void)file;
  return -1;
}

/**
  * @brief Get file status (stub)
  * @param [in] file File descriptor (unused)
  * @param [out] st Pointer to stat structure
  * @return 0 (success)
  * @details Sets st_mode to S_IFCHR (character device) for console, a stub for CN0575’s Newlib needs.
  */
int _fstat(int file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

/**
  * @brief Check if file descriptor is a terminal (stub)
  * @param [in] file File descriptor (unused)
  * @return 1 (true)
  * @details Returns 1 to indicate a terminal device (LPUART1), satisfying Newlib for CN0575.
  */
int _isatty(int file)
{
  (void)file;
  return 1;
}

/**
  * @brief Seek within file (stub)
  * @param [in] file File descriptor (unused)
  * @param [in] ptr Offset (unused)
  * @param [in] dir Seek direction (unused)
  * @return 0 (fixed position)
  * @details Returns 0 as CN0575 has no file system, a minimal stub for Newlib.
  */
int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

/**
  * @brief Open file (stub)
  * @param [in] path File path (unused)
  * @param [in] flags Open flags (unused)
  * @param ... Additional arguments (unused)
  * @return -1 (error)
  * @details Always returns -1 as CN0575 lacks file system support, required by Newlib.
  */
int _open(char *path, int flags, ...)
{
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

/**
  * @brief Wait for process (stub)
  * @param [in] status Pointer to status (unused)
  * @return -1 (error)
  * @details Sets errno to ECHILD and returns -1, as CN0575 has no process support.
  */
int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

/**
  * @brief Remove file (stub)
  * @param [in] name File name (unused)
  * @return -1 (error)
  * @details Sets errno to ENOENT and returns -1, as CN0575 has no file system.
  */
int _unlink(char *name)
{
  (void)name;
  errno = ENOENT;
  return -1;
}

/**
  * @brief Get process times (stub)
  * @param [in] buf Pointer to tms structure (unused)
  * @return -1 (error)
  * @details Returns -1 as CN0575 lacks process timing support, a Newlib stub.
  */
int _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

/**
  * @brief Get file status by name (stub)
  * @param [in] file File name (unused)
  * @param [out] st Pointer to stat structure
  * @return 0 (success)
  * @details Sets st_mode to S_IFCHR, a stub for CN0575’s console-like behavior.
  */
int _stat(char *file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

/**
  * @brief Create hard link (stub)
  * @param [in] old Source path (unused)
  * @param [in] new Target path (unused)
  * @return -1 (error)
  * @details Sets errno to EMLINK and returns -1, as CN0575 has no file system.
  */
int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

/**
  * @brief Fork process (stub)
  * @return -1 (error)
  * @details Sets errno to EAGAIN and returns -1, as CN0575 has no multi-process support.
  */
int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

/**
  * @brief Execute program (stub)
  * @param [in] name Program name (unused)
  * @param [in] argv Argument vector (unused)
  * @param [in] env Environment variables (unused)
  * @return -1 (error)
  * @details Sets errno to ENOMEM and returns -1, as CN0575 lacks process execution.
  */
int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}

/** @}*/
